baseurl = "https://mattle24.github.io/mattle24_blog/public/"
relativeURLs = false
languageCode = "en-us"
title = "Blog"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "All Posts"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Home"
    url = "https://mattle24.github.io"
    weight = 2

[params]
    description = ""

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "../public/images/favicon.png"

    [params.logo]
    url = "favicon.png"
    width = 50
    height = 50
    alt = "Logo"
